[package]
name = "verona-rt-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cmake = "0.1.50"

[build-dependencies]
cmake = "0.1.50"

[features]
systematic_testing = []
flight_recorder = []