gather:
    ./gather_imgs.sh

# Build report TeX sources
tex:
    mkdir -p dist
    pandoc report.md -so dist/report.tex --pdf-engine=xelatex --citeproc --lua-filter=minted.lua

# Build report PDF
pdf: tex
    latexmk

# Remove build artifacts
clean:
    rm -rf ./dist
    rm -rf ./svg-inkscape

longbench:
    cargo bench -p verona-rt --bench micro -- --test
    cargo bench -p verona-rt --bench micro -- --measurement-time 200 --discard-baseline