gather:
    ./gather_imgs.sh

html: report_html
report_html:
    pandoc report.md -so report.html --citeproc

pdf: report_pdf
report_pdf:
    pandoc report.md -o report.pdf --pdf-engine=xelatex --citeproc

tex: report_tex
report_tex:
    pandoc report.md -so report.tex --pdf-engine=xelatex --citeproc

longbench:
    cargo bench -p verona-rt --bench micro -- --test
    cargo bench -p verona-rt --bench micro -- --measurement-time 200 --discard-baseline